---
- name: Populate oo_masters_to_config host group
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Evaluate oo_masters_to_config
    add_host:
      name: "{{ item }}"
      groups: oo_masters_to_config
      ansible_ssh_user: root
    with_items: oo_host_group_exp | default([])

- include: ../../common/openshift-master/config.yml
  vars:
    openshift_cluster_id: "{{ cluster_id }}"
    openshift_debug_level: 4
    openshift_deployment_type: "{{ deployment_type }}"
    openshift_hostname: "{{ gce_private_ip }}"
