---
- name: deploy monitoring image build files
  file: dest=/usr/local/etc/containers/monitoring_container mode=755 state=directory

- name: deploy monitoring image build files
  copy: "src=monitoring_container/{{ item.name }} dest=/usr/local/etc/containers/monitoring_container/{{ item.name }} mode={{ item.mode }}"
  with_items:
    - { name: 'Dockerfile',              mode: '644' }
    - { name: 'register-with-zabbix.rb', mode: '755' }

- name: deploy monitoring image build templates
  template: "src=monitoring_container/{{ item.name }}.j2 dest=/usr/local/etc/containers/monitoring_container/{{ item.name }} mode={{ item.mode }}"
  with_items:
    - { name: 'start.rb',                mode: '755' }
