---
- name: Verify Ansible version is greater than 1.8.0 and not 1.9.0 and not 1.9.0.1
  assert:
    that:
    - ansible_version | version_compare('1.8.0', 'ge')
    - ansible_version | version_compare('1.9.0', 'ne')
    - ansible_version | version_compare('1.9.0.1', 'ne')

- name: Ensure PyYaml is installed
  action: "{{ ansible_pkg_mgr }} name=PyYAML state=present"

- name: Gather Cluster facts and set is_containerized if needed
  openshift_facts:
    role: common
    local_facts:
      is_containerized: "{{ openshift_containerized | default(None) }}"
