---
- import_playbook: config.yml

- name: Create persistent volumes
  hosts: oo_first_master
  roles:
  - role: openshift_persistent_volumes
    when:
    - openshift_hosted_registry_storage_kind | default(none) == 'glusterfs' or openshift_hosted_registry_storage_glusterfs_swap

- import_playbook: ../../openshift-hosted/private/openshift_hosted_registry.yml

- import_playbook: ../../openshift-hosted/private/openshift_hosted_wait_for_pods.yml

- import_playbook: ../../openshift-hosted/private/openshift_hosted_registry_storage.yml
