---
galaxy_info:
  author: Thomas Wiest
  description: Common base RHEL atomic configurations
  company: Red Hat
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
  # This is the role's PRIVATE counterpart, which is used.
  - ../../../../../atomic_private/ansible/roles/atomic_proxy
