---
- name: Terminate instance(s)
  hosts: localhost
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - set_fact: scratch_group=tag_env-host-type_{{ cluster_id }}-openshift-node
  - add_host:
      name: "{{ item }}"
      groups: oo_nodes_to_terminate
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    with_items: groups[scratch_group] | default([]) | difference(['localhost'])

  - set_fact: scratch_group=tag_env-host-type_{{ cluster_id }}-openshift-master
  - add_host:
      name: "{{ item }}"
      groups: oo_masters_to_terminate
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    with_items: groups[scratch_group] | default([]) | difference(['localhost'])

- include: ../openshift-node/terminate.yml

- include: ../openshift-master/terminate.yml
