---
- name: delete the node scale groups
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Alert user to variables needed - clusterid
    debug:
      msg: "openshift_aws_clusterid={{ openshift_aws_clusterid | default('default') }}"

  - name: Alert user to variables needed - region
    debug:
      msg: "openshift_aws_region={{ openshift_aws_region | default('us-east-1') }}"

  - name: delete the node groups
    import_role:
      name: openshift_aws
      tasks_from: uninstall_nodes.yml
