---
deployment_vars:
  origin:
    # fedora, since centos requires marketplace
    image: ami-acd999c4
    region: us-east-1
    ssh_user: fedora
    sudo: yes
    keypair: libra
    type: m3.large
    security_groups: [ 'public' ]
    vpc_subnet:
    assign_public_ip:
  online:
    # private ami
    image: ami-906240f8
    region: us-east-1
    ssh_user: root
    sudo: no
    keypair: mmcgrath_libra
    type: m3.large
    security_groups: [ 'int-v3' ]
    vpc_subnet: subnet-987c0def
    assign_public_ip: yes
  enterprise:
    # rhel-7.1, requires cloud access subscription
    image: ami-10663b78
    region: us-east-1
    ssh_user: ec2-user
    sudo: yes
    keypair: libra
    type: m3.large
    security_groups: [ 'public' ]
    vpc_subnet:
    assign_public_ip:
