---
- name: Ensure the generated_configs directory present
  file:
    path: "{{ openshift_generated_configs_dir }}/{{ item.master_cert_subdir }}"
    state: directory
    mode: 0700
  with_items: masters_needing_certs

- file:
    src: "{{ openshift_master_ca_cert }}"
    dest: "{{ openshift_generated_configs_dir }}/{{ item.master_cert_subdir }}/ca.crt"
  with_items: masters_needing_certs

- name: Create the master certificates if they do not already exist
  command: >
    {{ openshift.common.admin_binary }} create-master-certs
      --hostnames={{ item.openshift.common.hostname }},{{ item.openshift.common.public_hostname }}
      --master={{ item.openshift.master.api_url }}
      --public-master={{ item.openshift.master.public_api_url }}
      --cert-dir={{ openshift_generated_configs_dir }}/{{ item.master_cert_subdir }}
      --overwrite=false
  args:
    creates: "{{ openshift_generated_configs_dir }}/{{ item.master_cert_subdir }}/master.server.crt"
  with_items: masters_needing_certs
