---
- name: Configure master instances
  hosts: oo_masters_to_config
  vars:
    openshift_sdn_master_url: https://{{ openshift.common.hostname }}:4001
  roles:
  - openshift_master
  - { role: openshift_sdn_master, when: openshift.common.use_openshift_sdn | bool }
  tasks:
  - name: Create group for deployment type
    group_by: key=oo_masters_deployment_type_{{ openshift.common.deployment_type }}
    changed_when: False

# Additional instance config for online deployments
- name: Additional instance config
  hosts: oo_masters_deployment_type_online
  roles:
  - pods
  - os_env_extras
