- name: Restart master system
  # https://github.com/ansible/ansible/issues/10616
  shell: sleep 2 && shutdown -r now "OpenShift Ansible master rolling restart"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
# When cluster_method != pacemaker we can ensure the api_port is
# available.
- name: Wait for master API to come back online
  become: no
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      state=started
      delay=10
      port="{{ openshift.master.api_port }}"
  when: openshift.master.cluster_method != 'pacemaker'
# When cluster_method is pacemaker we can only ensure that the host
# restarted successfully.
- name: Wait for master to start
  become: no
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      state=started
      delay=10
  when: openshift.master.cluster_method == 'pacemaker'
