---
# TODO: package this?
- name: Copy static master scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0500
  with_items:
  - scripts/docker/master-exec
  - scripts/docker/master-logs
  - scripts/docker/master-restart

- name: Ensure cri-tools installed
  package:
    name: cri-tools
    state: present
  when: not openshift_is_atomic | bool
