---
# TODO: package this?
- name: Copy static master scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/bin/"
    mode: 0500
  with_items:
  - scripts/docker/master-logs
  - scripts/docker/master-restart
