---
- name: Create the OpenStack resources for cluster installation
  hosts: localhost
  tasks:
  - name: provision cluster
    include_role:
      name: openshift_openstack
      tasks_from: provision.yml


# NOTE(shadower): Bring in the host groups:
- name: evaluate groups
  include: ../../init/evaluate_groups.yml


- name: Wait for the nodes and gather their facts
  hosts: oo_all_hosts
  become: yes
  # NOTE: The nodes may not be up yet, don't gather facts here.
  # They'll be collected after `wait_for_connection`.
  gather_facts: no
  tasks:
  - name: Wait for the the nodes to come up
    wait_for_connection:

  - name: Gather facts for the new nodes
    setup:

- name: set common facts
  include: ../../init/facts.yml


# NOTE(shadower): the (internal) DNS must be functional at this point!!
# That will have happened in provision.yml if nsupdate was configured.

# TODO(shadower): consider splitting this up so people can stop here
# and configure their DNS if they have to.
- name: Populate the DNS entries
  hosts: localhost
  tasks:
  - name: Populate DNS entries
    include_role:
      name: openshift_openstack
      tasks_from: populate-dns.yml
    when:
    - openshift_openstack_external_nsupdate_keys is defined
    - openshift_openstack_external_nsupdate_keys.private is defined or openshift_openstack_external_nsupdate_keys.public is defined

- name: Prepare the Nodes in the cluster for installation
  hosts: oo_all_hosts
  become: yes
  gather_facts: yes
  roles:
  - role: rhel_subscribe
    when:
    - ansible_distribution == "RedHat"
    - lookup('env', 'rhel_subscription_user') | default(rhsub_user | default(False, True), True)
    - lookup('env', 'rhel_subscription_pass') | default(rhsub_pass | default(False, True), True)

  tasks:
  - name: Install dependencies
    include_role:
      name: openshift_openstack
      tasks_from: node-packages.yml

  - name: Configure Node
    include_role:
      name: openshift_openstack
      tasks_from: node-configuration.yml
