---
- name: make puppet conf dir
  file: >
    dest={{ oo_proxy_puppet_volume_dir }}/etc/puppet
    mode=755
    owner=root
    group=root
    state=directory

- name: upload puppet auth config
  copy: >
    src=puppet/auth.conf
    dest={{ oo_proxy_puppet_volume_dir }}/etc/puppet/auth.conf
    mode=0644
    owner=root
    group=root

- name: upload puppet config
  template: >
    src=puppet/puppet.conf.j2
    dest={{ oo_proxy_puppet_volume_dir }}/etc/puppet/puppet.conf
    mode=0644
    owner=root
    group=root
