---
- name: Ensure openshift-monitor-availability project
  oc_project:
    state: present
    name: openshift-monitor-availability
    description: Openshift availability monitoring applications.

- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-monitor-availability-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy files to temp directory
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ mktemp.stdout }}"

- name: Ensure Prometheus role exists
  oc_obj:
    name: prometheus-k8s
    namespace: openshift-monitor-availability
    kind: Role
    state: present
    - "{{ mktemp.stdout }}/prometheus-k8s-role.yaml"

- name: Ensure Prometheus role binding exists
  oc_obj:
    name: prometheus-k8s
    namespace: openshift-monitor-availability
    kind: RoleBinding
    state: present
    - "{{ mktemp.stdout }}/prometheus-k8s-role-binding.yaml"

- name: Create Monitor app template
  oc_obj:
    name: openshift-monitor-app-create
    namespace: openshift-monitor-availability
    kind: Template
    state: present
    - "{{ mktemp.stdout }}/monitor-app-create.yaml"

- name: Create Monitor app
    namespace: openshift-monitor-availability
    template_name: openshift-monitor-app-create
    params:
      IMAGE: "{{ openshift_monitor_app_create_image }}"
      RUN_INTERVAL: "{{ openshift_monitor_app_create_run_interval }}"
      TIMEOUT: "{{ openshift_monitor_app_create_timeout }}"
      LOG_LEVEL: "{{ openshift_monitor_app_create_log_level }}"

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
