---
- name: Template Create Template
  zbx_template:
    zbx_server: "{{ server }}"
    zbx_user: "{{ user }}"
    zbx_password: "{{ password }}"
    name: "{{ template.name }}"
  register: created_template


- set_fact:
    lzbx_applications: "{{ template.zitems | oo_select_keys_from_list(['applications']) | oo_flatten | unique }}"

- name: Create Application
  zbx_application:
    zbx_server: "{{ server }}"
    zbx_user: "{{ user }}"
    zbx_password: "{{ password }}"
    name: "{{ item }}"
    template_name: "{{ template.name }}"
  with_items: lzbx_applications
  register: created_application
  when: template.zitems is defined

- name: Create Items
  zbx_item:
    zbx_server: "{{ server }}"
    zbx_user: "{{ user }}"
    zbx_password: "{{ password }}"
    key: "{{ item.key }}"
    name: "{{ item.name | default(item.key, true) }}"
    value_type: "{{ item.value_type | default('int') }}"
    template_name: "{{ template.name }}"
    applications: "{{ item.applications }}"
  with_items: template.zitems
  register: created_items
  when: template.zitems is defined

- name: Create Triggers
  zbx_trigger:
    zbx_server: "{{ server }}"
    zbx_user: "{{ user }}"
    zbx_password: "{{ password }}"
    description: "{{ item.description }}"
    dependencies: "{{ item.dependencies | default([], true) }}"
    expression: "{{ item.expression }}"
    priority: "{{ item.priority }}"
  with_items: template.ztriggers
  when: template.ztriggers is defined
