---
- yum:
    name: openshift-ansible-inventory
    state: present

- template:
    src: multi_ec2.yaml.j2
    dest: /etc/ansible/multi_ec2.yaml
    group: "{{ oo_inventory_group }}"
    owner: "{{ oo_inventory_owner }}"
    mode: "0640"

- file:
    state: directory
    dest: /etc/ansible/inventory
    owner: root
    group: libra_ops
    mode: 0750

- file:
    state: link
    src: /usr/share/ansible/inventory/multi_ec2.py
    dest: /etc/ansible/inventory/multi_ec2.py
    owner: root
    group: libra_ops

# This cron uses the above location to call its job
- name: Cron to keep cache fresh
  cron:
    name: 'multi_ec2_inventory'
    minute: '*/10'
    job: '/usr/share/ansible/inventory/multi_ec2.py --refresh-cache &> /dev/null'
  when: oo_cron_refresh_cache is defined and oo_cron_refresh_cache

- lineinfile:
    dest: /etc/ansible/ansible.cfg
    backrefs: yes
    regexp: '^(hostfile|inventory)( *)='
    line: '\1\2= /etc/ansible/inventory'

- name: setting ec2.ini destination_format
  lineinfile:
    dest: /usr/share/ansible/inventory/aws/ec2.ini
    regexp: '^destination_format *='
    line: "destination_format = {{ oo_ec2_destination_format }}"
  when: oo_ec2_destination_format is defined

- name: setting ec2.ini destination_format_tags
  lineinfile:
    dest: /usr/share/ansible/inventory/aws/ec2.ini
    regexp: '^destination_format_tags *='
    line: "destination_format_tags = {{ oo_ec2_destination_format_tags }}"
  when: oo_ec2_destination_format_tags is defined

- name: Set cache location
  file:
    state: directory
    dest: "{{ oo_inventory_cache_location | dirname }}"
    owner: root
    group: libra_ops
    recurse: yes
    mode: '2750'
  when: oo_inventory_cache_location is defined

