---
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-glusterfs-ansible-XXXXXX
  register: mktemp
  changed_when: False
  check_mode: no

- include: glusterfs_config.yml
  when:
  - g_glusterfs_hosts | default([]) | count > 0

- include: glusterfs_registry.yml
  when:
  - g_glusterfs_registry_hosts | default([]) | count > 0
  - "openshift.hosted.registry.storage.kind == 'glusterfs'"

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
  check_mode: no
