---
- name: Set hosted facts
  openshift_facts:
    role: hosted
    openshift_env: "{{ item | oo_openshift_env }}"
  no_log: true
  with_items:
  - "{{ hostvars[inventory_hostname] }}"
  - "{{ hostvars }}"
