---
- name: Check cert expirys on host
  openshift_cert_expiry:
    warning_days: "{{ warning_days|int }}"
    config_base: "{{ config_base }}"
    show_all: "{{ show_all|bool }}"
  register: check_results

- name: Generate expiration report HTML
  become: no
  run_once: yes
  template:
    src: cert-expiry-table.html.j2
    dest: "{{ html_report_path }}"
  delegate_to: localhost
  when: "{{ generate_html_report|bool }}"

- name: Generate expiration results JSON
  become: no
  run_once: yes
  template:
    src: save_json_results.j2
    dest: "{{ json_results_path }}"
  delegate_to: localhost
  when: "{{ save_json_results|bool }}"
