---
- name: Set node facts
  openshift_facts:
    role: "{{ item.role }}"
    local_facts: "{{ item.local_facts }}"
  with_items:
  - role: node
    local_facts:
      annotations: "{{ openshift_node_annotations | default(none) }}"
      registry_url: "{{ oreg_url_node | default(oreg_url) | default(None) }}"
      ovs_image: "{{ osn_ovs_image | default(None) }}"
      dns_ip: "{{ openshift_dns_ip | default(none) | node_get_dns_ip(hostvars[inventory_hostname])}}"
      env_vars: "{{ openshift_node_env_vars | default(None) }}"
