---
openshift_storageclass_defaults:
  aws:
    name: gp2
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: gp2
  gce:
    name: standard
    provisioner: kubernetes.io/gce-pd
    parameters:
      type: pd-standard

openshift_storageclass_name: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['name'] }}"
openshift_storageclass_provisioner: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['provisioner'] }}"
openshift_storageclass_parameters: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['parameters'] }}"
