---
- name: "populate oo_hosts_to_config host group if needed"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Evaluate oo_host_group_exp
    add_host: "name={{ item }} groups=oo_hosts_to_config"
    with_items: "{{ oo_host_group_exp | default('') }}"
    when: oo_host_group_exp is defined

- name: "Gather facts for masters in {{ oo_env }}"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-master"
  connection: ssh
  user: root

- name: "Set OO sepcific facts on localhost (for later use)"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Setting openshift_master_ips fact on localhost
      set_fact:
        openshift_master_ips: "{{ hostvars
            | oo_select_keys(groups['tag_env-host-type_' + oo_env + '-openshift-master'])
            | oo_collect(attribute='ansible_default_ipv4.address') }}"
      when: groups['tag_env-host-type_' + oo_env + '-openshift-master'] is defined

- name: "Configure instances"
  hosts: oo_hosts_to_config
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - base_os
    - repos
    - docker
    - {
        role: openshift_node,
        openshift_master_ips: "{{ hostvars['localhost'].openshift_master_ips | default(['']) }}",
        # TODO: add openshift_Master_public_ips
        openshift_env: {{ "oo_env" }}
        # TODO: openshift_public_ip: set to aws instance public ip
      }
