---
# determine if yum install of node pkgs will work
- when:
    - not containerized
  block:

    - name: main packages for enterprise
      when:
        - deployment_type == "openshift-enterprise"
      check_yum_update:
        packages:
          - atomic-openshift
          - atomic-openshift-node
          - atomic-openshift-sdn-ovs
      register: r

    - set_fact:
        oo_preflight_check_results: "{{ oo_preflight_check_results + [r|combine({'_task': 'main packages for enterprise'})] }}"

    - name: main packages for origin
      when:
        - deployment_type == "origin"
      check_yum_update:
        packages:
          - origin
          - origin-node
          - origin-sdn-ovs
      register: r

    - set_fact:
        oo_preflight_check_results: "{{ oo_preflight_check_results + [r|combine({'_task': 'main packages for origin'})] }}"

    - name: other node packages
      check_yum_update:
        packages:
          - docker
          - PyYAML
          - firewalld
          - iptables
          - iptables-services
          - nfs-utils
          - ntp
          - yum-utils
          - dnsmasq
          - libselinux-python
          - ceph-common
          - glusterfs-fuse
          - iscsi-initiator-utils
          - pyparted
          - python-httplib2
          - openssl
          - flannel
          - bind
      register: r

    - set_fact:
        oo_preflight_check_results: "{{ oo_preflight_check_results + [r|combine({'_task': 'other node packages'})] }}"
