---
- name: Create cloudprovider config dir
  file:
    path: "{{ openshift.common.config_base }}/cloudprovider"
    state: directory
  when: has_cloudprovider | bool

- include: openstack.yml
  when: cloudprovider_is_openstack | bool

- include: aws.yml
  when: cloudprovider_is_aws | bool
