---
# fixme: Once openshift stops resolving hostnames for node queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  hostname: name={{ openshift_bind_ip }}

- name: Configure local facts file
  file: path=/etc/ansible/facts.d/ state=directory mode=0750

- name: Set common OpenShift facts
  include: set_facts.yml
  facts:
  - { section: common, option: env, value: "{{ openshift_env | default('default') }}" }
  - { section: common, option: host_type, value: "{{ openshift_host_type }}" }
  - { section: common, option: debug_level, value: "{{ openshift_debug_level }}" }

- name: Add KUBECONFIG to .bash_profile for user root
  lineinfile:
    dest: /root/.bash_profile
    regexp: "KUBECONFIG="
    line: "export KUBECONFIG=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig"
    state: present
    insertafter: EOF
