---
- name: Install OpenShift Master package
  yum: pkg=openshift-master state=installed

- name: Configure firewall for OpenShift Master
  include: "{{ role_path | dirname }}/openshift_common/tasks/firewall.yml"
  allow:
  - service: etcd embedded
    port: 4001/tcp
  - service: etcd peer
    port: 7001/tcp
  - service: OpenShift api https
    port: 8443/tcp
  - service: OpenShift web console https
    port: 8444/tcp
  deny:
  - service: OpenShift api http
    port: 8080/tcp

- name: Configure OpenShift settings
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: '^OPTIONS='
    line: "OPTIONS=\"--public-master={{ openshift_public_ip }} --nodes={{ openshift_node_ips
          | join(',') }}  --loglevel={{ openshift_master_debug_level }}\""
  notify:
  - restart openshift-master

- name: Set default registry url
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: '^IMAGES='
    line: "IMAGES={{ openshift_registry_url }}"
  when: openshift_registry_url is defined
  notify:
  - restart openshift-master

- name: Set master OpenShift facts
  include: "{{ role_path | dirname }}/openshift_common/tasks/set_facts.yml"
  facts:
  - section: master
    option: debug_level
    value: "{{ openshift_master_debug_level }}" }
  - section: master
    option: public_ip
    value: "{{ openshift_public_ip }}" }
  - section: master
    option: externally_managed
    value: "{{ openshift_master_manage_service_externally }}" }

- name: Start and enable openshift-master
  service: name=openshift-master enabled=yes state=started
  when: not openshift_master_manage_service_externally

- name: Disable openshift-master if openshift-master is managed externally
  service: name=openshift-master enabled=false
  when: openshift_master_manage_service_externally
