---
# tasks file for openshift_master
- name: Install Origin
  yum: pkg=openshift-master state=installed

  # fixme: Once openshift stops resolving hostnames for node queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  command: /usr/bin/hostname {{ oo_bind_ip }}

- name: Configure OpenShift Master settings
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - regex: '^OPTIONS='
      line: "OPTIONS=\"--public-master={{ oo_public_ip }} --nodes={{ oo_node_ips | join(',') }}  --loglevel=5\""
  notify:
    - restart openshift-master

# Open etcd embedded, etcd embedded peer, openshift api, and
# openshift client ports
- name: Open firewalld ports for openshift-master
  firewalld: port={{ item[0] }} permanent={{ item[1] }} state=enabled
  with_nested:
  - [ 4001/tcp, 7001/tcp, 8443/tcp, 8444/tcp ]
  - [ true, false ]

# Disable previously exposed ports that are no longer needed
- name: Close firewalld ports for openshift-master that are no longer needed
  firewalld: port={{ item[0] }} permanent={{ item[1] }} state=enabled
  with_nested:
  - [ 8080/tcp ]
  - [ true, false ]

- name: Enable OpenShift
  service: name=openshift-master enabled=yes state=started
