---
# TODO: allow for overriding default ports where possible

- name: Install OpenShift Master package
  yum: pkg=openshift-master state=installed

- name: Configure firewall for OpenShift Master
  include: "{{ role_path | dirname }}/openshift_common/tasks/firewall.yml"
  allow:
  - { service: etcd embedded, port: 4001/tcp}
  - { service: etcd peer, port: 7001/tcp}
  - { service: OpenShift api https, port: 8443/tcp}
  - { service: OpenShift web console https, port: 8444/tcp}
  deny:
  - { service: OpenShift api http, port: 8080/tcp }

# TODO: instead of setting openshift_node_ips here, we should gather the node
# info, and then add/update any nodes if needed using osc. Otherwise, we are
# restarting the openshift-master service everytime we add a node.
- name: Configure OpenShift settings
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: '^OPTIONS='
    line: "OPTIONS=\"--public-master={{ openshift_hostname }} --nodes={{ openshift_node_ips
              | join(',') }}  --loglevel={{ openshift_master_debug_level }}\""
  notify:
  - restart openshift-master

- name: Set default registry url
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: '^IMAGES='
    line: "IMAGES={{ openshift_registry_url }}"
  when: openshift_registry_url is defined
  notify:
  - restart openshift-master

- name: Set master OpenShift facts
  include: "{{ role_path | dirname }}/openshift_common/tasks/set_facts.yml"
  facts:
  - { section: master, option: debug_level, value: "{{ openshift_master_debug_level }}" }
  - { section: master, option: public_ip, value: "{{ openshift_public_ip }}" }
  - { section: master, option: externally_managed, value: "{{ openshift_master_manage_service_externally }}" }

- name: Start and enable openshift-master
  service: name=openshift-master enabled=yes state=started
  when: not openshift_master_manage_service_externally
  register: result

#TODO: remove this when origin PR #1204 has landed in OSE
- name: need to pause here, otherwise we attempt to copy certificates generated by the master before they are generated
  pause: seconds=30
  when: result | changed

- name: Disable openshift-master if openshift-master is managed externally
  service: name=openshift-master enabled=false
  when: openshift_master_manage_service_externally

# TODO: create an os_vars role that has generic env related config and move
# the root kubeconfig setting there, cannot use dependencies to force ordering
# with openshift_node and openshift_master because the way conditional
# dependencies work with current ansible would also exclude the
# openshift_common dependency.
- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: 0700
- name: Configure root user kubeconfig
  command: cp /var/lib/openshift/openshift.local.certificates/admin/.kubeconfig /root/.kube/.kubeconfig
  args:
    creates: /root/.kube/.kubeconfig
