---
# tasks file for openshift_master
- name: Install Origin
  yum: pkg=openshift-master state=installed

  # fixme: Once openshift stops resolving hostnames for node queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  command: /usr/bin/hostname {{ oo_bind_ip }}

- name: Configure OpenShift Master settings
  lineinfile:
    dest: /etc/sysconfig/openshift-master
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - { regex: '^OPTIONS=', line: 'OPTIONS=\"--public-master={{ oo_public_ip }} --nodes={{ oo_node_ips | join(",") }}  --loglevel=5\"' }
  notify:
    - restart openshift-master

- name: Open firewalld port for etcd embedded in OpenShift
  firewalld: port=4001/tcp permanent=false state=enabled

- name: Save firewalld port for etcd embedded in
  firewalld: port=4001/tcp permanent=true state=enabled

- name: Open firewalld port for OpenShift
  firewalld: port=8443/tcp permanent=false state=enabled

- name: Save firewalld port for OpenShift
  firewalld: port=8443/tcp permanent=true state=enabled

- name: Enable OpenShift
  service: name=openshift-master enabled=yes state=started
