# Playbook to upgrade Docker to the max allowable version for an OpenShift cluster.
#
# Currently only supports upgrading 1.9.x to >= 1.10.x.
- include: ../../initialize_groups.yml

- include: ../../../../common/openshift-cluster/evaluate_groups.yml
  vars:
    # Do not allow adding hosts during upgrade.
    g_new_master_hosts: []
    g_new_node_hosts: []
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_deployment_type: "{{ deployment_type }}"

- include: ../../../../common/openshift-cluster/upgrades/initialize_nodes_to_upgrade.yml

- include: docker_upgrade.yml
