# ---
# # This must be evaluated after cluster_hosts.yml has been evaluated on
# # 'localhost' to generate l_oo_all_hosts and then subsequently
# # evaluated again on the generated hosts group (l_oo_all_hosts).
# - include: evaluate_groups.yml
#   tags:
#   - always

# # Initialize cluster facts for oo_all_hosts using the openshift_facts
# # role followed by the 'common' role
# - include: initialize_facts.yml
#   tags:
#   - always

# # Get the version to install from the first master, then synchronize
# # that variable across all in oo_all_hosts
# - include: initialize_openshift_version.yml
#   tags:
#   - always

# # Earlier 'initialize_facts' included the openshift_facts role and
# # used the openshift_facts module with the 'role' parameter set to
# # 'common'. Now we're applying the openshift_facts role AGAIN but just
# # to the subset of oo_all_hosts which require configuring.
# - name: Load openshift_facts
#   hosts: oo_etcd_to_config:oo_masters_to_config:oo_nodes_to_config
#   roles:
#     - openshift_facts

- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Check cert expirys on host
      openshift_cert_expiry:
        warning_days: 1500
        show_all: true
