---
- include: evaluate_groups.yml

  - name: Evaluate oo_lb_to_config
    add_host:
      name: "{{ item }}"
      groups: oo_lb_to_config
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
    with_items: groups[g_lb_group] | default(groups[g_masters_group]) | default([])

- include: ../openshift-etcd/config.yml

- include: ../openshift-master/config.yml

- include: ../openshift-node/config.yml
  vars:
    osn_cluster_dns_domain: "{{ hostvars[groups.oo_first_master.0].openshift.dns.domain }}"
    osn_cluster_dns_ip: "{{ hostvars[groups.oo_first_master.0].openshift.dns.ip }}"
