---
- include: evaluate_groups.yml

- name: Configure docker hosts
  hosts: oo_nodes_to_config
  vars:
    docker_additional_registries: "{{ lookup('oo_option', 'docker_additional_registries') | oo_split }}"
    docker_insecure_registries: "{{ lookup('oo_option',  'docker_insecure_registries') | oo_split }}"
    docker_blocked_registries: "{{ lookup('oo_option', 'docker_blocked_registries') | oo_split }}"
  roles:
  - openshift_facts
  - openshift_docker

- include: ../openshift-node/config.yml

- name: Gather facts
  hosts: oo_etcd_to_config:oo_masters_to_config:oo_nodes_to_config
  roles:
  - openshift_facts

- name: Update master count
  hosts: oo_masters:!oo_masters_to_config
  serial: 1
  roles:
  - openshift_facts
  post_tasks:
  - openshift_facts:
      role: master
      local_facts:
        master_count: "{{ openshift_master_count | default(groups.oo_masters | length) }}"
  - name: Update master count
    lineinfile:
      dest: "{{ openshift.common.config_base}}/master/master-config.yaml"
      regexp: '^  masterCount:.*$'
      line: "  masterCount: {{ openshift.master.master_count }}"
    notify:
    - restart master api
    - restart master controllers
  handlers:
  - name: restart master api
    service: name={{ openshift.common.service_type }}-master-controllers state=restarted
    notify: verify api server
  - name: restart master controllers
    service: name={{ openshift.common.service_type }}-master-controllers state=restarted
  - name: verify api server
    command: >
      curl -k --head --silent {{ openshift.master.api_url }}
    register: api_available_output
    until: api_available_output.stdout.find("200 OK") != -1
    retries: 120
    delay: 1
    changed_when: false

- include: ../openshift-master/config.yml

- include: ../openshift-node/config.yml
