---
- name: Initialization Checkpoint Start
  hosts: all
  gather_facts: false
  roles:
  - installer_checkpoint
  tasks:
  - name: Set install initialization 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_initialize:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- include: evaluate_groups.yml
  tags:
  - always

- include: initialize_facts.yml
  tags:
  - always

- include: sanity_checks.yml
  tags:
  - always

- include: validate_hostnames.yml
  tags:
  - node

- include: initialize_openshift_repos.yml
  tags:
  - always

- include: initialize_openshift_version.yml
  tags:
  - always

- name: Initialization Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set install initialization 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_initialize:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
