---
galaxy_info:
  author: Jhon Honce
  description: OpenShift Master
  company: Red Hat, Inc.
  license: ASL 2.0
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
- { role: openshift_common }
