---
- name: Verify Requirements
  # REVIEW: what's the proper group to use: OSEv3, g_all_hosts or something else?
  hosts: OSEv3
  roles:
    - openshift_health_checker
  post_tasks:
    - action: openshift_health_check
      args:
        checks:
          - disk_availability
          - memory_availability

- include: openshift-cluster/config.yml
