apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocs
  namespace: operator-lifecycle-manager
spec:
  sourceType: internal
  configMap: ocs
  displayName: Open Cloud Services
  publisher: Red Hat

