---
- name: install some useful packages
  yum: name={{ item }}
  with_items:
  - git
  - python-pip
  - unzip
  - python-psphere
  - ansible
  - telnet
  - ack

- name: download Tower setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-2.1.1.tar.gz dest=/opt/ force=no

- name: extract Tower
  unarchive: src=/opt/ansible-tower-setup-2.1.1.tar.gz dest=/opt copy=no creates=ansible-tower-setup-2.1.1

- name: Open firewalld port for http
  firewalld: port=80/tcp permanent=true state=enabled

- name: Open firewalld port for https
  firewalld: port=443/tcp permanent=true state=enabled

- name: Open firewalld port for https
  firewalld: port=8080/tcp permanent=true state=enabled

