---
- name: "Verify SELinux is enforcing"
  fail:
    msg: "SELinux is required for OpenShift and has been detected as '{{ ansible_selinux.config_mode }}'"
  when: ansible_selinux.config_mode != "enforcing"

- include: container-storage-setup.yml

- include: node-network.yml
