---
# check-cert-expiry.yaml - A utility for cluster ops to scan through
# (critical) certificates for the ongoing operations of a cluster.

# We do not support all Ansible versions. This is our safety net.
- include: ../../common/openshift-cluster/verify_ansible_version.yml

- name: Generate the l_oo_all_hosts group
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - include_vars: cluster_hosts.yml
  - add_host:
      name: "{{ item }}"
      groups: l_oo_all_hosts
    with_items: "{{ g_all_hosts | default([]) }}"

# This may seem redundant, running `include_vars` again on the list of
# hosts in the group 'l_oo_all_hosts' which we just created. But the
# fact of the matter is that if we don't re-run include_vars on the
# new host group we created, then they will not have access to those
# same group variables they were birthed from.
#
# Go ahead and try to 'debug: var=g_all_hosts' later on (without this
# play) and you'll find that the result is UNDEFINED VARIABLE.
- name: Inject cluster hosts variables into l_oo_all_hosts
  hosts: l_oo_all_hosts
  gather_facts: no
  tasks:
  - include_vars: cluster_hosts.yml

# This is where the actual business gets started:
- include: ../../common/openshift-cluster/check-cert-expiry.yaml
