---
- name: Disable all repositories
  command: subscription-manager repos --disable="*"

- name: Enable RHEL repositories
  command: subscription-manager repos \
               --enable="rhel-7-server-rpms" \
               --enable="rhel-7-server-extras-rpms" \
               --enable="rhel-7-server-ose-{{ openshift_release }}-rpms" \
               --enable="rhel-7-fast-datapath-rpms"
  register: subscribe_repos
  until: subscribe_repos | succeeded
