---
- name: Install OpenShift Node package
  yum: pkg=openshift-node state=installed

- name: Set OpenShift node facts
  include: "{{ role_path | dirname }}/openshift_common/tasks/set_facts.yml"
  facts:
  - { section: node, option: debug_level, value: "{{ openshift_node_debug_level }}" }

- local_action: command /usr/bin/mktemp -d /tmp/openshift-ansible-XXXXXXX
  register: mktemp

- name: Retrieve OpenShift Master credentials
  local_action: command /usr/bin/rsync --compress --archive --rsh 'ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' root@{{ openshift_master_public_ips[0] }}:/var/lib/openshift/openshift.local.certificates/admin/ {{ mktemp.stdout }}
  ignore_errors: yes

- file: path=/var/lib/openshift/openshift.local.certificates/admin state=directory

- name: Store OpenShift Master credentials
  local_action: command /usr/bin/rsync --compress --archive --rsh 'ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' {{ mktemp.stdout }}/ root@{{ openshift_public_ip }}:/var/lib/openshift/openshift.local.certificates/admin
  ignore_errors: yes
  # fixme: Once the openshift_cluster playbook is published state should be started
  # Always bounce service to pick up new credentials
  notify: restart openshift-node

- local_action: file name={{ mktemp.stdout }} state=absent

- name: Configure firewall for OpenShift Node
  include: "{{ role_path | dirname }}/openshift_common/tasks/firewall.yml"
  allow:
  - { service: OpenShift kubelet, port: 10250/tcp }

- name: Configure OpenShift Node settings
  lineinfile:
    dest: /etc/sysconfig/openshift-node
    regexp: '^OPTIONS='
    line: "OPTIONS=\"--master=http://{{ openshift_master_ips[0] }}:8080 --loglevel={{ openshift_node_debug_level }}\""
  notify:
  - restart openshift-node

- name: Start and enable openshift-node
  service: name=openshift-node enabled=yes state=started
  when: not openshift_node_manage_service_externally

- name: Disable openshift-node if openshift-node is managed externally
  service: name=openshift-node enabled=false
  when: openshift_node_manage_service_externally
