---
# This task runs async to save time while the node is being configured
- name: Pre-pull node image
  command: "{{ openshift_container_cli }} pull {{ osn_image }}"
  # 10 minutes to pull the image
  async: 600
  poll: 0
  register: image_prepull
  # Pre-pull is not critical to upgrade.  When upgrading from 3.9, crictl may
  # not be installed yet or may not match the installed crio version.
  ignore_errors: true

# This task runs async to save time while other downloads proceed
- name: pre-pull pod image
  command: "{{ openshift_container_cli }} pull {{ osn_pod_image }}"
  environment:
    NO_PROXY: "{{ openshift.common.no_proxy | default('') }}"
  # 10 minutes to pull the image
  async: 600
  poll: 0
  register: pod_image_prepull
  # Pre-pull is not critical to upgrade.  When upgrading from 3.9, crictl may
  # not be installed yet or may not match the installed crio version.
  ignore_errors: true
