---
- name: restart master
  systemd: name={{ openshift.common.service_type }}-master state=restarted
  when: (openshift.master.ha is not defined or not openshift.master.ha | bool) and (not (master_service_status_changed | default(false) | bool))
  notify: Verify API Server

- name: Verify API Server
  uri:
    url: "{{ openshift.master.api_url }}/healthz/ready"
    return_content: yes
    status_code: 200
  register: api_available_output
  until: "'ok' in api_available_output.content"
  retries: 120
  delay: 1
  changed_when: false
