---
r_openshift_storage_nfs_os_firewall_deny: []
r_openshift_storage_nfs_os_firewall_allow:
- service: nfs
  port: "2049/tcp"
  cond: true

openshift:
  hosted:
    registry:
      storage:
        nfs:
          directory: "/exports"
          options: "*(rw,root_squash)"
        volume:
          name: "registry"
    metrics:
      deploy: False
      storage:
        nfs:
          directory: "/exports"
          options: "*(rw,root_squash)"
        volume:
          name: "metrics"
