- name: "populate oo_hosts_to_config host group if needed"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Evaluate oo_host_group_exp
    add_host: "name={{ item }} groups=oo_hosts_to_config"
    with_items: "{{ oo_host_group_exp | default('') }}"
    when: oo_host_group_exp is defined

- name: "Configure instances"
  hosts: oo_hosts_to_config
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - ../../../roles/base_os
