---
# Install default storage classes in GCE & AWS
- name: storageclass template
  template:
    src: storageclass.j2
    dest: /tmp/storageclass
  run_once: true

- name: Ensure storageclass object
  oc_obj:
    kind: storageclass
    name: "{{ openshift_storageclass_name }}"
    files:
    - /tmp/storageclass
  run_once: true
