---
# tasks file for openshift_master
- name: Install Origin
  yum: pkg=openshift state=installed

- name: Configure Origin settings
  lineinfile: >
    dest=/etc/sysconfig/openshift
    regexp={{ item.regex }}
    line="{{ item.line }}"
  with_items:
    - { regex: '^OPENSHIFT_MASTER',  line: 'OPENSHIFT_MASTER=\"{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}\"' }
    - { regex: '^OPENSHIFT_BIND_ADDR', line: 'OPENSHIFT_BIND_ADDR=\"{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}\"'}
  notify:
    - restart openshift-master

- name: Enable OpenShift
  service: name=openshift enabled=yes state=started

- name: Open firewalld port for Origin
  firewalld: port=8080/tcp permanent=false state=enabled

- name: Save firewalld port for Origin
  firewalld: port=8080/tcp permanent=true state=enabled

