---
- name: Populate oo_masters_to_config host group
  hosts: localhost
  gather_facts: no
  tasks:
  - add_host:
      name: "{{ item }}"
      groups: oo_masters_to_config
    with_items: groups['masters']

- include: ../../common/openshift-master/config.yml
  vars:
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_debug_level: 4
    openshift_deployment_type: "{{ deployment_type }}"
