---
# TODO: add some logic to provide a sane default for  this var, use the
# roles assigned to the host and the values of other variables to
# determine if we should manage the service within this role
openshift_node_manage_service_externally: false
openshift_node_debug_level: "{{ openshift_debug_level | default(0) }}"
