---
- name: deploy puppet image build files
  file: dest=/usr/local/etc/containers/puppet_container mode=755 state=directory

- name: deploy puppet image build files
  copy: "src=puppet_container/{{ item.name }} dest=/usr/local/etc/containers/puppet_container/{{ item.name }} mode={{ item.mode }}"
  with_items:
    - { name: 'Dockerfile', mode: '644' }
    - { name: 'service.rb', mode: '755' }
    - { name: 'start.rb',   mode: '755' }
