---
r_openshift_loadbalancer_firewall_enabled: "{{ os_firewall_enabled | default(True) }}"
r_openshift_loadbalancer_use_firewalld: "{{ os_firewall_use_firewalld | default(False) }}"

r_openshift_loadbalancer_os_firewall_deny: []
r_openshift_loadbalancer_os_firewall_allow:
- service: haproxy stats
  port: "9000/tcp"
- service: haproxy balance
  port: "{{ openshift_master_api_port }}/tcp"
- service: nuage mon
  port: "{{ nuage_mon_rest_server_port | default(9443) }}/tcp"
  cond: "{{ r_openshift_lb_use_nuage | bool }}"

openshift_docker_service_name: "docker"

# NOTE
# r_openshift_lb_use_nuage_default may be defined external to this role.
# openshift_use_nuage, if defined, may affect other roles or play behavior.
r_openshift_lb_use_nuage_default: "{{ openshift_use_nuage | default(False) }}"
r_openshift_lb_use_nuage: "{{ r_openshift_lb_use_nuage_default }}"
