---
- name: Disable excluders
  hosts: oo_masters_to_config
  gather_facts: no
  tasks:
  - include_role:
      name: openshift_excluder
      tasks_from: verify_upgrade
  - include_role:
      name: openshift_excluder
      tasks_from: disable
    vars:
      openshift_excluder_package_state: latest
      docker_excluder_package_state: latest
