---
- include: ../evaluate_groups.yml
  vars:
    # Do not allow adding hosts during upgrade.
    g_new_master_hosts: []
    g_new_node_hosts: []
    openshift_cluster_id: "{{ cluster_id | default('default') }}"

- include: ../initialize_oo_option_facts.yml

- include: ../initialize_facts.yml

- name: Ensure clean repo cache in the event repos have been changed manually
  hosts: oo_all_hosts
  tags:
  - pre_upgrade
  tasks:
  - name: Clean package cache
    command: "{{ ansible_pkg_mgr }} clean all"
    when: not openshift.common.is_atomic | bool
    args:
      warn: no

- name: Ensure firewall is not switched during upgrade
  hosts: oo_all_hosts
  tasks:
  - name: Check if iptables is running
    command: systemctl status iptables
    changed_when: false
    failed_when: false
    register: service_iptables_status

  - name: Set fact os_firewall_use_firewalld FALSE for iptables
    set_fact:
      os_firewall_use_firewalld: false
    when: "'Active: active' in service_iptables_status.stdout"
