---
- debug: var=ctp_template

- name: Create Application
  zbxapi:
    server: "{{ ctp_zserver }}"
    user: "{{ ctp_zuser }}"
    password: "{{ ctp_zpassword }}"
    zbx_class: Application
    state: present
    params:
      name: "{{ ctp_template.application['name'] }}"
      hostid: 10085
      search:
        name: "{{ ctp_template.application['name'] }}"
  register: ctp_created_application

- debug: var=ctp_created_application
