---
- name: restart openvswitch
  service: name=openvswitch state=restarted
  when: not (ovs_service_status_changed | default(false) | bool)
  notify:
  - restart openvswitch pause

- name: restart openvswitch pause
  pause: seconds=15
  when: openshift.common.is_containerized | bool

- name: restart node
  service: name={{ openshift.common.service_type }}-node state=restarted
  when: not (node_service_status_changed | default(false) | bool)

