---
- command: >
    echo "{{openshift_logging_fluentd_nodeselector.keys()[0]}}"
  register: openshift_logging_fluentd_nodeselector_key

- command: >
    echo "{{openshift_logging_fluentd_nodeselector.values()[0]}}"
  register: openshift_logging_fluentd_nodeselector_value

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get node -o jsonpath='{.items[*].metadata.name}'
  register: fluentd_hosts
  when: "'--all' in openshift_logging_fluentd_hosts"

- name: stop fluentd
  include: label_node.yaml
  vars:
    host: "{{fluentd_host}}"
    label: "{{openshift_logging_fluentd_nodeselector_key.stdout}}"
    unlabel: True
  with_items: "{{(fluentd_hosts.stdout_lines is defined) | ternary(fluentd_hosts.stdout_lines, openshift_logging_fluentd_hosts)}}"
  loop_control:
    loop_var: fluentd_host

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=es -o name -n {{openshift_logging_namespace}}
  register: es_dc

- name: stop elasticsearch
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{es_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=kibana -o name -n {{openshift_logging_namespace}}
  register: kibana_dc

- name: stop kibana
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{kibana_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=curator -o name -n {{openshift_logging_namespace}}
  register: curator_dc

- name: stop curator
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{curator_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=es-ops -o name -n {{openshift_logging_namespace}}
  register: es_dc

- name: stop elasticsearch-ops
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{es_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=kibana-ops -o name -n {{openshift_logging_namespace}}
  register: kibana_dc

- name: stop kibana-ops
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{kibana_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops

- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=curator-ops -o name -n {{openshift_logging_namespace}}
  register: curator_dc

- name: stop curator-ops
  include: scale.yaml
  vars:
    desired: 0
  with_items: "{{curator_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops
