---
- name: Stop the Cluster
  include: stop_cluster.yaml

- name: Upgrade logging
  include: install_logging.yaml
  vars:
    start_cluster: False

# ensure that ES is running
- command: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=es -o name -n {{openshift_logging_namespace}}
  register: es_dc
  check_mode: no

- name: start elasticsearch
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{es_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- copy:
    src: es_migration.sh
    dest: {{mktemp.stdout}}/es_migration.sh

- name: Run upgrade scripts
  command: >
    sh {{mktemp.stdout}}/es_migration.sh {{openshift.common.config_base}}/logging/ca.crt {{openshift.common.config_base}}/logging/system.admin.key {{openshift.common.config_base}}/logging/system.admin.crt {{openshift_logging_es_host}} {{openshift_logging_es_port}} {{openshift_logging_namespace}}

- name: Start up rest of cluster
  include: start_cluster.yaml
