---
- name: Check if descheduler cronjob exists
  oc_obj:
    state: list
    kind: cronjob
    name: "{{ openshift_descheduler_cronjob_name }}"
    namespace: "{{ openshift_descheduler_namespace }}"
  register: descheduler_cronjob

- name: Upgrade descheduler cronjob
  include_tasks: install_descheduler.yaml
  when:
  - descheduler_cronjob.results.results[0] != {}
