- name: "populate oo_hosts_to_config host group if needed"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Evaluate oo_host_group_exp if it's set
    add_host: "name={{ item }} groups=oo_hosts_to_config"
    with_items: "{{ oo_host_group_exp | default('') }}"
    when: oo_host_group_exp is defined

- name: "Gather facts for minions in {{ oo_env }}"
  hosts: "tag_env-host-type-{{ oo_env }}-os3-minion"
  connection: ssh
  user: root

- name: "Set OO sepcific facts on localhost (for later use)"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Setting oo_minion_ips fact on localhost
      set_fact:
        oo_minion_ips: "{{ hostvars
            | oo_select_keys(groups['tag_env-host-type-' + oo_env + '-os3-minion'])
            | oo_collect(attribute='ansible_eth0.ipv4.address') }}"
      when: groups['tag_env-host-type-' + oo_env + '-os3-minion'] is defined

- name: "Configure instances"
  hosts: oo_hosts_to_config
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - ../../../roles/base_os
    - ../../../roles/repos
    - ../../../roles/etcd
    - {
        role: ../../../roles/kubernetes_apiserver,
        oo_minion_ips: "{{ hostvars['localhost'].oo_minion_ips | default(['']) }}"
      }
    - ../../../roles/kubernetes_controller_manager
    - ../../../roles/pods
