---
- name: update ca trust
  command: update-ca-trust
  notify:
  - restart docker after updating ca trust

- name: restart docker after updating ca trust
  service:
    name: docker
    state: restarted
  when: not openshift_certificates_redeploy | default(false) | bool
